name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: exercise/src
    - name: Build VendingMachine App
      run: dotnet build --no-restore
      working-directory: exercise/src
    - name: Test VendingMachine App
      run: dotnet test --no-build --verbosity normal
      working-directory: exercise/src
    - name: Deploy VendingMachine App
      run: dotnet publish VendingMachine.csproj -c Release -o ~/exercise/app/ --runtime win10-x64 --self-contained true -p:PublishSingleFile=true
      working-directory: exercise/src/VendingMachine/
